/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    __TestPage__: typeof import('./components/pages/__TestPage__.vue')['default']
    BurgerButton: typeof import('./components/Header/BurgerButton.vue')['default']
    FilesVaultPage: typeof import('./components/pages/FilesVaultPage.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InProccessTask: typeof import('./components/pages/MainPage.vuecessTask.vue')['default']
    InputCustom: typeof import('./components/inputCustom.vue')['default']
    LoginInput: typeof import('./components/pages/LoginPage/LoginInput.vue')['default']
    LoginPage: typeof import('./components/pages/LoginPage/LoginPage.vue')['default']
    MainPage: typeof import('./components/pages/MainPage.vue')['default']
    Note: typeof import('./components/notes/note.vue')['default']
    NotesPage: typeof import('./components/pages/NotesPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/Header/SideBar.vue')['default']
    Task: typeof import('./components/Task.vue')['default']
    TestPage: typeof import('./components/pages/__TestPage__.vue')['default']
    TodayTask: typeof import('./components/TodayTask.vue')['default']
    ZovInput: typeof import('./components/ZOV/ZovInput.vue')['default']
    ZOVInput: typeof import('./components/pages/LoginPage/ZOV-Input.vue')['default']
  }
}
