/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilesVaultPage: typeof import('./components/pages/FilesVaultPage.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InProccessTask: typeof im./components/pages/MainPage.vuecessTask.vue')['default']
    InputCustom: typeof import('./components/inputCustom.vue')['default']
    MainPage: typeof import('./components/pages/MainPage.vue')['default']
    Note: typeof import('./components/notes/note.vue')['default']
    NotesPage: typeof import('./components/pages/NotesPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./components/Task.vue')['default']
    TodayTask: typeof import('./components/TodayTask.vue')['default']
  }
}
